// REQUISIÇÕES DE USUÁRIOS
POST  http://localhost:3000/login
Content-Type: application/json

{
    "username":"Gustavo Sampaio"
}

//
###
GET http://localhost:3000/logout
Content-Type:  application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR3VzdGF2byBTYW1wYWlvIiwiaWF0IjoxNjM3NjI4NTY4LCJleHAiOjE2Mzc2MzQ1Njh9.VYrSxtjWoEnr5PKJeH1T0vN5syL9-K0SEmw68niBwac

///USERS
//LISTAR USER
###
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR3VzdGF2byBTYW1wYWlvIiwiaWF0IjoxNjM3NjI4NTY4LCJleHAiOjE2Mzc2MzQ1Njh9.VYrSxtjWoEnr5PKJeH1T0vN5syL9-K0SEmw68niBwac

//BUSCAR USER
###
GET http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR3VzdGF2byBTYW1wYWlvIiwiaWF0IjoxNjM3NjI4MTE1LCJleHAiOjE2Mzc2MzQxMTV9.ER89Skb9MA2WF3wcjGyqW5LsB4lnLjF4pE3LjVqrL94

//CRIAR USER
###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR3VzdGF2byBTYW1wYWlvIiwiaWF0IjoxNjM3NjI4MTE1LCJleHAiOjE2Mzc2MzQxMTV9.ER89Skb9MA2WF3wcjGyqW5LsB4lnLjF4pE3LjVqrL94

{
    "Nome": "Rajesh Ota",
    "Email": "rajesh@globo.com",
    "Idade": "20",
    "CPF": "123456789",
    "Role": 2
}

//ATUALIZAR USERS
###
PUT http://localhost:3000/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR3VzdGF2byBTYW1wYWlvIiwiaWF0IjoxNjM3NjI4NTQxLCJleHAiOjE2Mzc2MzQ1NDF9.Ds3xByvwQ9TWTyfvYn6MXFuWOyRy3dOF5o0Wl_zKfOM

{   
    "Nome": "Vinicius Barros",
    "Email": "rajesh@globo.com",
    "Idade": "20",
    "CPF": "123456789"
}

//DELETE USERS
###
DELETE http://localhost:3000/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR3VzdGF2byBTYW1wYWlvIiwiaWF0IjoxNjM3NjI4NTY4LCJleHAiOjE2Mzc2MzQ1Njh9.VYrSxtjWoEnr5PKJeH1T0vN5syL9-K0SEmw68niBwac

/// REQUISIÇÕES DE ITENS
// LISTAR ITENS
###
GET http://localhost:3000/itens/
Content-Type: application/json
Authorization: Bearer 

//BUSCAR ITEM
###
GET http://localhost:3000/itens/3
Content-Type: application/json
Authorization: Bearer 

//CRIAR LISTA
###
POST http://localhost:3000/itens
Content-Type: application/json
Authorization: Bearer 

{
  "Nome": "Espada Longa",
  "Tipo": "Ataque",
  "Efeito": "+25 Ataque",
  "Decrição": "Espada GPC"
}

//ATUALIZAR ITEM
###
PUT http://localhost:3000/itens/2
Content-Type: application/json
Authorization: Bearer 

{   
  "Nome": "Espada Curta",
  "Tipo": "Ataque",
  "Efeito": "+25 Ataque",
  "Decrição": "Espada GPC"
}

//DELETE ITENS
###
DELETE http://localhost:3000/itens/5
Content-Type: application/json
Authorization: Bearer 

//LISTAR ROOMS
###
GET http://localhost:3000/rooms/
Content-Type: application/json
Authorization: Bearer 

//BUSCAR UM ROOM
###
GET http://localhost:3000/rooms/1
Content-Type: application/json
Authorization: Bearer 

//CRIAR ROOMS
###
POST http://localhost:3000/rooms
Content-Type: application/json
Authorization: Bearer 

{
  "Nome": "Ilha da Wano",
  "OwnerId": "3",
  "Password": "wano1234",
  "Amount": "3"
}

//ATUALIZAR ROOMS
###
PUT http://localhost:3000/rooms/2
Content-Type: application/json
Authorization: Bearer 

{
    "Nome": "Ilha Nublar",
    "OwnerId": "5",
    "Password": "nublar123",
    "Amount": "7"
}

//DELETE ROOMS
###
DELETE http://localhost:3000/rooms/1
Content-Type: application/json
Authorization: Bearer 

//CARDS LIST
###
GET http://localhost:3000/cards/
Content-Type: application/json
Authorization: Bearer 

//CARDS CREATE
###
POST http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer 
{
  "Nome": "Zayon",
  "Tribe": "Ladino",
  "Life": "1000",
  "Atack": "290",
  "Defense": "150",
  "Description": "Maluco doido"
}

//CARDS UPDATE
###
PUT http://localhost:3000/cards/1
Content-Type: application/json
Authorization: Bearer 

{
  "Nome": "Zayon",
  "Tribe": "Ladino",
  "Life": "1000",
  "Atack": "290",
  "Defense": "150",
  "Description": "Maluco doido"
}

// CARDS DELETE
###
DELETE http://localhost:3000/cards/2
Content-Type: application/json
Authorization: Bearer 
